### PR TITLE
Feat: signin a user with email and password

### LINKED ISSUE #40: Feat: User Sign In with Email and Password
## Description

As a registered user (vendor or buyer), I want to be able to sign in to the e-commerce platform using my email and password so that I can access my account and its respective features.

The sign-in process should securely authenticate the user's credentials and provide appropriate responses and error handling.

### Acceptance Criteria

- [x] Implement a user sign-in API endpoint
- [x] Validate user input (email and password)
- [x] Retrieve the user record from the database based on the provided email
- [x] Verify the provided password against the securely stored password hash
- [x] Generate and return an authentication token (e.g., JSON Web Token) upon successful sign-in
- [x] Return appropriate success or error responses
- [x] Implement input sanitization

## Developer Notes

- Define the API endpoint and request/response payloads
- Implement input validation and sanitization measures
- Retrieve user records securely from the database
- Use a secure password verification method (e.g., bcrypt, argon2)
- Generate and manage authentication tokens (e.g., JWT)
- Write unit tests to cover different scenarios and edge cases

## Related Issues

- #39 Feat: Register User (Vendors & Buyers) 

## Definition of Done

- User sign-in API endpoint is implemented and functional
- User input validation and sanitization measures are in place
- User credentials are securely verified against stored data
- Authentication tokens are generated and returned upon successful sign-in
- Appropriate success and error responses are returned
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation is updated

### PR DESCRIPTION
**Pull request by Ndevu12**
### Description
This PR introduces a new feature that allows users to sign in using their email and password.
Also it Implement error handling for cases where the user tries to sign in with an invalid email or password.

**Changes**

- Added a new endpoint POST /user/signin that handles user sign-in.
- Implemented a function to validate the user's email and password.
- If the validation is successful, the server responds with a cookie containing the user's access token.

**Test Plan**

- Added unit tests for the POST /user/signin endpoint in signin.test.ts.
- The tests cover the case where a user signs in with a valid email and password.
- After all tests, the database connection is closed to prevent any hanging test cases.

### CODE REVIEW

**Comment by faid-terence** [comment]
@Ndevu12 !!What's the progres ?

**Comment by Ndevu12** [comment]
Sorry I forgot to send JWT_SECRET_KEY.

But you can find it on slack now.

**Comment by faid-terence** [comment]
@Ndevu12 !
please squash the commit messages!!

**Comment by Ndevu12** [comment]
@faid-terence 
That is what Am going to be working on

**Review by faid-terence — CHANGES_REQUESTED** [review]
We can't merge this PR !, Please squash commit messages !

**Comment by Ndevu12** [comment]
Now we have one commit

**Pull request closed without merging**
