### PR TITLE
ch: Updated README file

### PR DESCRIPTION
**Pull request by aimedivin**
#### What does this PR do?

This PR updates the README file with detailed information about the E-commerce backend API repository.

#### Description of Task to be completed?

The task involved:
- Updating the README file to provide comprehensive documentation for the E-commerce backend API repository. 
- Including project description, setup instructions locally on machine, technologies used, authors, and testing procedures.

#### Any background context you want to provide?

This README file will serves as a guide for developers to understand the project, set it up locally, and contribute effectively.

### CODE REVIEW

**Comment by MC-Knight** [comment]
Good job 👍🏿

**Review by MC-Knight — APPROVED** [review]

**Review by elijahladdie — CHANGES_REQUESTED** [review]
Hi @aimedivin there few changes like 
Screenshot 2024-04-25 103013
change `nmp ` to be `npm`
and on routes 
Screenshot 2024-04-25 103101
you you didn't specify those routes. you can temporally comment them since we don't have them yet

**Review by elijahladdie — APPROVED** [review]
@aimedivin Well done!

**Review by MC-Knight — CHANGES_REQUESTED** [review]
@aimedivin use current devolop branch version

**Review by faid-terence — CHANGES_REQUESTED** [review]
@aimedivin !
Please have the updated version of develop !!

**Review by Ndevu12 — APPROVED** [review]
Good

**Review by MC-Knight — APPROVED** [review]

**Review by faid-terence — APPROVED** [review]
Nice Work @aimedivin !

**Pull request merged**
