### PR TITLE
Chore: Jest Setup and Coverage Configuration

### PR DESCRIPTION
**Pull request by maxCastro1**
### **Original PR #15** 

This pull request adds the Jest testing setup for our project and includes a test for the root route of our Express application.

**Changes include:**

- Setup of Jest and TypeScript dependencies.
- Configuration of Jest for TypeScript in jest.config.js.
- Creation of __tests__ directory for unit tests.
- Addition of test script to package.json.
- A unit test for the root ('/') route of the application.

**Testing:**
npm test

### **Changes**
- created new branch ,
-  modified gitignore to not push coverage folder ,
-  and added a line to stop the server when done with testing

### CODE REVIEW

**Review by aimedivin — APPROVED** [review]

**Comment by elijahladdie** [comment]
@maxCastro1  Can you try to resolve these conflicts please

**Comment by MC-Knight** [comment]
Good job 👍

**Review by MC-Knight — APPROVED** [review]

**Review by faid-terence — CHANGES_REQUESTED** [review]
Please update the PR Title @maxCastro1 !

**Review by elijahladdie — APPROVED** [review]
@maxCastro1, Well done!

**Review by GSinseswa721 — APPROVED** [review]

**Review by Calebgisa72 — APPROVED** [review]
Good job!!

**Review by faid-terence — CHANGES_REQUESTED** [review]
@maxCastro1 !
Please rebase with develop and rename your branch , example: `ch-jest-configuration`

**Pull request closed without merging**
