### PR TITLE
Feat-implment-wish list

### LINKED ISSUE #71: Feat: Buyer should be able to manage their wish list
Description:

The backend needs to handle the addition of items to the buyer's wishlist, including storing the wishlist in the buyer's account and sending a confirmation message to the frontend.

Acceptance Criteria:
 

- [x] Implement a POST request endpoint to add an item to the buyer's wishlist.
- [x] When a POST request is made:
- [x] The item should be added to the buyer's wishlist.
- [x] The product details (name, price, image) should be retrieved from the database.
- [x] The updated wishlist should be stored with the buyer's entity and have a relationship with the buyer.
- [x] A confirmation message should be sent to the frontend to be displayed to the buyer.

Developer Notes:

- Validate that the buyer is logged in before processing the request.
- Implement logic to add the item to the buyer's wishlist.
- Retrieve the product details from the database based on the item being added.
- Store the updated wishlist in the buyer's account entity.

Related Issues:
Feat: Role-Based Access Control (RBAC) #45

Definition of Done:

- A POST request endpoint is implemented and functional for adding items to the buyer's wishlist.
- The item is successfully added to the buyer's wishlist.
- Product details (name, price, image) are retrieved from the database and associated with the item.
- The updated wishlist is stored in the buyer's account entity and has a proper relationship with the buyer.
- A confirmation message is sent to the frontend and displayed to the buyer.
- Buyer login validation is implemented to ensure only logged-in buyers can add items to their wishlist.

### PR DESCRIPTION
**Pull request by Calebgisa72**
What does this PR do?

- This PR introduces key features and enhancements related to wish list functionality in the backend. The aim is to allow buyers to manage their wish lists effectively, including adding, retrieving, and removing products from their wish lists, along with comprehensive error handling.

Description of Task Completed:

1. Wish List Endpoints:

- Implemented endpoints for adding a product to the wish list, retrieving all products in the wish list, removing a product from the wish list, and clearing the entire wish list.
- These endpoints provide buyers with control over their wish lists, enhancing their shopping experience.

2. Tests:

- Added tests for all the wish list endpoints and made sure the run.
- Added tests for error handling to ensure robustness and reliability across the wish list functionality.

How should this be manually tested?

- git clone https://github.com/atlp-rwanda/knights-ecomm-be.git
- cd knights-ecomm-be
- npm install
- npm run dev
- npm run test

### CODE REVIEW

**Comment by faid-terence** [comment]
@Calebgisa72 
Resolve the conflict !!

**Review by aimedivin — DISMISSED** [review]

**Comment by Calebgisa72** [comment]
> @Calebgisa72 Resolve the conflict !!

Done

**Review by MC-Knight — APPROVED** [review]

**Review by elijahladdie — APPROVED** [review]

**Comment by Ndevu12** [comment]
Too many commits

**Comment by faid-terence** [comment]
@Calebgisa72 
Can you squash those commit messages and keep only one ! that is related to your issue

**Review by maxCastro1 — APPROVED** [review]

**Pull request closed without merging**
