### PR TITLE
ch-Add a global error handler middleware

### PR DESCRIPTION
**Pull request by Calebgisa72**
What does this PR do?
This pull request implements a global error handling middleware in the knights-ecomm-be project to enhance error management and user experience.

Description of Task Completed:
The task accomplished in this pull request involves:

- Implementing a middleware function to catch unhandled errors globally.
- Defining a custom error class (CustomError) to encapsulate error details including status code and status.
- Developing an error handling middleware (errorHandler) to provide informative error responses.
- Integrating the error handling middleware into the Express application to handle errors across all routes.

How should this be manually tested?
To manually test all the changes made in this pull request, follow these steps:
git clone -b branch-name https://github.com/your-username/knights-ecomm-be.git

cd knights-ecomm-be
npm i
npm run dev
Make a request using postman.

### CODE REVIEW

**Review by elijahladdie — APPROVED** [review]
@Calebgisa72 Looks Good🎉!

**Review by aimedivin — APPROVED** [review]

**Review by faid-terence — CHANGES_REQUESTED** [review]
You should have updated version of develop @Calebgisa72 !

**Review by MC-Knight — APPROVED** [review]

**Review by elijahladdie — CHANGES_REQUESTED** [review]
@Calebgisa72, You are not using errorHandler in the project root which is resulting error can you please include it in src/index.ts
it should be something like this `app.use(errorHandler);`

**Review by faid-terence — APPROVED** [review]
Nice Work @Calebgisa72 !

**Pull request merged**
